name: Build & Push Docker images
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  Build-And-Push-Image:
    runs-on:
      - ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./grpc-generate-java-node
            image: ghcr.io/MOES-Media/grpc-generate-java-node

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Login To GHCR.io
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CI_TOKEN }}
      - name: Prepare Release
        run: yarn install --immutable --immutable-cache --check-cache && yarn release:prepare
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.package-version.outputs.current-version }}

