name: Build & Push Docker images
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  Build-And-Push-Image:
    runs-on:
      - ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./grpc-generate-java-node
            image: ghcr.io/MOES-Media/grpc-generate-java-node

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Login To GHCR.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: MOES-Media
          password: ${{ secrets.CI_TOKEN }}
      - name: Prepare Release
        run: yarn install --immutable --immutable-cache --check-cache && yarn release:prepare
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.package-version.outputs.current-version }}
          labels: ${{ steps.meta.outputs.labels }}

